/**
 * CloserEdge AI — Stripe Checkout & Billing Helpers
 *
 * Exports functions for creating checkout sessions, customer portal sessions,
 * and querying subscription status. Consumed by the app's billing routes.
 *
 * Requires:
 *   - STRIPE_SECRET_KEY in env
 *   - scripts/stripe-products.json (generated by stripe-setup.ts)
 */

import Stripe from "stripe";
import * as fs from "node:fs";
import * as path from "node:path";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type AgentType = "eden" | "crest" | "lexis" | "haven" | "forge" | "nora";

export type TierName = "foundation" | "pro" | "elite";

export type AddOnKey =
  | "voice"
  | "mentor"
  | "mls_data"
  | "social_media"
  | "seasonal_campaigns"
  | "review_automation"
  | "investor_reporting";

export interface PriceIds {
  foundation_monthly: string;
  foundation_setup: string;
  pro_monthly: string;
  pro_setup: string;
  elite_monthly: string;
  elite_setup: string;
}

export interface ProductEntry {
  product_id: string;
  prices: PriceIds;
}

export interface AddOnEntry {
  product_id: string;
  price_id: string;
}

export interface StripeProductsConfig {
  products: Record<AgentType, ProductEntry>;
  addons: Record<AddOnKey, AddOnEntry>;
}

export interface CheckoutSessionOptions {
  agentType: AgentType;
  tier: TierName;
  customerEmail: string;
  /** Optional existing Stripe customer ID. If provided, email is ignored. */
  customerId?: string;
  /** Add-on keys to include in the subscription. */
  addOns?: AddOnKey[];
  /** URL to redirect to after successful checkout. */
  successUrl: string;
  /** URL to redirect to if the customer cancels. */
  cancelUrl: string;
  /** Whether to include the one-time setup fee. Defaults to true. */
  includeSetupFee?: boolean;
  /** Optional trial period in days. */
  trialPeriodDays?: number;
  /** Optional metadata to attach to the subscription. */
  metadata?: Record<string, string>;
}

export interface CheckoutSessionResult {
  sessionId: string;
  url: string | null;
}

export interface PortalSessionResult {
  url: string;
}

export type SubscriptionStatus =
  | "active"
  | "past_due"
  | "unpaid"
  | "canceled"
  | "incomplete"
  | "incomplete_expired"
  | "trialing"
  | "paused";

export interface SubscriptionInfo {
  id: string;
  status: SubscriptionStatus;
  currentPeriodStart: Date;
  currentPeriodEnd: Date;
  cancelAtPeriodEnd: boolean;
  canceledAt: Date | null;
  items: SubscriptionItemInfo[];
}

export interface SubscriptionItemInfo {
  priceId: string;
  productId: string;
  quantity: number | null;
  unitAmount: number | null;
  interval: string | null;
  nickname: string | null;
}

// ---------------------------------------------------------------------------
// Stripe client singleton
// ---------------------------------------------------------------------------

let _stripe: Stripe | null = null;

function getStripe(): Stripe {
  if (_stripe) return _stripe;

  const secretKey = process.env.STRIPE_SECRET_KEY;
  if (!secretKey) {
    throw new Error(
      "STRIPE_SECRET_KEY environment variable is required for Stripe operations.",
    );
  }

  _stripe = new Stripe(secretKey, {
    apiVersion: "2025-04-30.basil",
    typescript: true,
  });
  return _stripe;
}

// ---------------------------------------------------------------------------
// Product config loader
// ---------------------------------------------------------------------------

let _config: StripeProductsConfig | null = null;

function loadProductsConfig(): StripeProductsConfig {
  if (_config) return _config;

  const configPath = path.resolve(__dirname, "stripe-products.json");
  if (!fs.existsSync(configPath)) {
    throw new Error(
      `Stripe products config not found at ${configPath}. Run stripe-setup.ts first.`,
    );
  }

  const raw = fs.readFileSync(configPath, "utf-8");
  _config = JSON.parse(raw) as StripeProductsConfig;

  // Validate that placeholder IDs are not present
  const firstProductId = Object.values(_config.products)[0]?.product_id;
  if (firstProductId === "prod_xxx") {
    throw new Error(
      "stripe-products.json contains placeholder IDs. Run stripe-setup.ts to populate real Stripe IDs.",
    );
  }

  return _config;
}

/**
 * Resolve the monthly price ID and setup price ID for a given agent + tier.
 */
function resolvePriceIds(
  agentType: AgentType,
  tier: TierName,
): { monthlyPriceId: string; setupPriceId: string } {
  const config = loadProductsConfig();
  const product = config.products[agentType];
  if (!product) {
    throw new Error(`Unknown agent type: ${agentType}`);
  }

  const monthlyKey = `${tier}_monthly` as keyof PriceIds;
  const setupKey = `${tier}_setup` as keyof PriceIds;

  const monthlyPriceId = product.prices[monthlyKey];
  const setupPriceId = product.prices[setupKey];

  if (!monthlyPriceId || !setupPriceId) {
    throw new Error(`Price IDs not found for ${agentType} / ${tier}`);
  }

  return { monthlyPriceId, setupPriceId };
}

// ---------------------------------------------------------------------------
// Exported functions
// ---------------------------------------------------------------------------

/**
 * Create a Stripe Checkout session for a new CloserEdge AI subscription.
 *
 * Includes the recurring monthly price as a subscription line item and
 * optionally the one-time setup fee. Any add-ons are added as additional
 * subscription line items.
 */
export async function createCheckoutSession(
  options: CheckoutSessionOptions,
): Promise<CheckoutSessionResult> {
  const stripe = getStripe();
  const config = loadProductsConfig();
  const { monthlyPriceId, setupPriceId } = resolvePriceIds(
    options.agentType,
    options.tier,
  );

  // Build subscription line items
  const lineItems: Stripe.Checkout.SessionCreateParams.LineItem[] = [
    {
      price: monthlyPriceId,
      quantity: 1,
    },
  ];

  // Add selected add-ons
  if (options.addOns && options.addOns.length > 0) {
    for (const addonKey of options.addOns) {
      const addon = config.addons[addonKey];
      if (!addon) {
        throw new Error(`Unknown add-on key: ${addonKey}`);
      }
      lineItems.push({
        price: addon.price_id,
        quantity: 1,
      });
    }
  }

  // Build the session params
  const sessionParams: Stripe.Checkout.SessionCreateParams = {
    mode: "subscription",
    line_items: lineItems,
    success_url: options.successUrl,
    cancel_url: options.cancelUrl,
    subscription_data: {
      metadata: {
        agent_type: options.agentType,
        tier: options.tier,
        platform: "closeredge",
        ...(options.metadata ?? {}),
      },
    },
    metadata: {
      agent_type: options.agentType,
      tier: options.tier,
      platform: "closeredge",
    },
    payment_method_types: ["card"],
    allow_promotion_codes: true,
  };

  // Customer identification
  if (options.customerId) {
    sessionParams.customer = options.customerId;
  } else {
    sessionParams.customer_email = options.customerEmail;
  }

  // Trial period
  if (options.trialPeriodDays && options.trialPeriodDays > 0) {
    sessionParams.subscription_data!.trial_period_days = options.trialPeriodDays;
  }

  // One-time setup fee as an invoice item via Checkout's invoice creation
  const includeSetup = options.includeSetupFee !== false;
  if (includeSetup) {
    // Stripe Checkout supports mixing subscription + one-time items when using
    // a single session by adding the setup fee as a line item with
    // price_data or a pre-created price that has no recurring interval.
    // We insert it as an additional line item — Stripe charges it on the
    // first invoice alongside the first subscription payment.
    lineItems.push({
      price: setupPriceId,
      quantity: 1,
    });
  }

  const session = await stripe.checkout.sessions.create(sessionParams);

  return {
    sessionId: session.id,
    url: session.url,
  };
}

/**
 * Convenience overload: create a checkout session with positional args.
 */
export async function createCheckoutSessionSimple(
  agentType: AgentType,
  tier: TierName,
  customerEmail: string,
  successUrl: string = "https://app.closeredge.ai/billing/success",
  cancelUrl: string = "https://app.closeredge.ai/billing/cancel",
): Promise<CheckoutSessionResult> {
  return createCheckoutSession({
    agentType,
    tier,
    customerEmail,
    successUrl,
    cancelUrl,
  });
}

/**
 * Create a Stripe Customer Portal session so the customer can manage
 * their subscription, update payment methods, view invoices, and cancel.
 *
 * @param stripeCustomerId - The Stripe customer ID (cus_xxx).
 * @param returnUrl - URL to redirect back to after the portal session.
 */
export async function createPortalSession(
  stripeCustomerId: string,
  returnUrl: string = "https://app.closeredge.ai/settings/billing",
): Promise<PortalSessionResult> {
  const stripe = getStripe();

  const session = await stripe.billingPortal.sessions.create({
    customer: stripeCustomerId,
    return_url: returnUrl,
  });

  return { url: session.url };
}

/**
 * Retrieve the current status of a Stripe subscription, including
 * line item details and cancellation state.
 *
 * @param stripeSubscriptionId - The Stripe subscription ID (sub_xxx).
 */
export async function getSubscriptionStatus(
  stripeSubscriptionId: string,
): Promise<SubscriptionInfo> {
  const stripe = getStripe();

  const subscription = await stripe.subscriptions.retrieve(stripeSubscriptionId, {
    expand: ["items.data.price.product"],
  });

  const items: SubscriptionItemInfo[] = subscription.items.data.map((item) => ({
    priceId: item.price.id,
    productId:
      typeof item.price.product === "string"
        ? item.price.product
        : item.price.product.id,
    quantity: item.quantity ?? null,
    unitAmount: item.price.unit_amount ?? null,
    interval: item.price.recurring?.interval ?? null,
    nickname: item.price.nickname ?? null,
  }));

  return {
    id: subscription.id,
    status: subscription.status as SubscriptionStatus,
    currentPeriodStart: new Date(subscription.current_period_start * 1000),
    currentPeriodEnd: new Date(subscription.current_period_end * 1000),
    cancelAtPeriodEnd: subscription.cancel_at_period_end,
    canceledAt: subscription.canceled_at
      ? new Date(subscription.canceled_at * 1000)
      : null,
    items,
  };
}

/**
 * Look up the CloserEdge agent type and tier from a Stripe subscription's metadata.
 * Returns null if the subscription was not created through CloserEdge checkout.
 */
export async function getSubscriptionAgentInfo(
  stripeSubscriptionId: string,
): Promise<{ agentType: AgentType; tier: TierName } | null> {
  const stripe = getStripe();
  const subscription = await stripe.subscriptions.retrieve(stripeSubscriptionId);

  const agentType = subscription.metadata.agent_type as AgentType | undefined;
  const tier = subscription.metadata.tier as TierName | undefined;

  if (!agentType || !tier) return null;

  return { agentType, tier };
}

/**
 * List all active subscriptions for a given Stripe customer.
 */
export async function listCustomerSubscriptions(
  stripeCustomerId: string,
): Promise<SubscriptionInfo[]> {
  const stripe = getStripe();

  const subscriptions = await stripe.subscriptions.list({
    customer: stripeCustomerId,
    status: "all",
    expand: ["data.items.data.price.product"],
    limit: 100,
  });

  return subscriptions.data.map((subscription) => {
    const items: SubscriptionItemInfo[] = subscription.items.data.map((item) => ({
      priceId: item.price.id,
      productId:
        typeof item.price.product === "string"
          ? item.price.product
          : item.price.product.id,
      quantity: item.quantity ?? null,
      unitAmount: item.price.unit_amount ?? null,
      interval: item.price.recurring?.interval ?? null,
      nickname: item.price.nickname ?? null,
    }));

    return {
      id: subscription.id,
      status: subscription.status as SubscriptionStatus,
      currentPeriodStart: new Date(subscription.current_period_start * 1000),
      currentPeriodEnd: new Date(subscription.current_period_end * 1000),
      cancelAtPeriodEnd: subscription.cancel_at_period_end,
      canceledAt: subscription.canceled_at
        ? new Date(subscription.canceled_at * 1000)
        : null,
      items,
    };
  });
}

/**
 * Export the loaded products config for use in other modules.
 */
export function getProductsConfig(): StripeProductsConfig {
  return loadProductsConfig();
}
